version: '3'

services:
  post_db:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "post_service_db"
    ports:
      - 5433:5432
