version: '3'

services:
  user_db:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "user_service_db"
    ports:
      - 5432:5432
